### PR TITLE
Fix negative margins

### PR DESCRIPTION
**Pull request by n-kort**
Negative margins weren't to spec 👓

### CODE REVIEW

**Comment by camslice** [comment]
I have run into this problem in a build before and ended implementing the same fix. Would be great to get this merged @jxnblk

**Comment by camslice** [comment]
This actually has already been implement in `basscss-margin`: https://github.com/basscss/basscss/blob/master/modules/margin/index.css

Would be great to get this applied for responsive margins

**Review by camslice — APPROVED** [review]
Looks good. postcss-preset-env still struggles with this. It's actually already been implemented in `basscss-margin`: https://github.com/basscss/basscss/blob/master/modules/margin/index.css

Just need to get this addon updated. I can't merge this code, so hopefully @jxnblk see these comments.

**Comment by jxnblk** [comment]
Thanks!

**Pull request merged**
